### ISSUE TITLE
nodejs-mobile fails to build on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by cyberiums** [janeasystems/nodejs-mobile#195]
During the `./tools/android_build.sh ~/android-ndk-r18b` process, it throws following error.

> ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/Users/pksingh/nodejs-mobile2/out/Release/torque] Error 1
make: *** [node] Error 2

**Comment by jaimecbernardo** [comment]
Hi @cyberiums ,
Could you please share the full build logo? Sharing a https://gist.github.com would be a good way of doing it.

**Comment by kongdexing** [comment]
I had the same error
`ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/Users/kongdexing/Desktop/MyProj/code/nodejs-mobile-git/nodejs-mobile/out/Release/torque] Error 1
rm 8b3fabe1e3eb4251f3eac8139324b7b48d695883.intermediate
make: *** [node] Error 2`

**Comment by jaimecbernardo** [comment]
Hi @kongdexing ,
Could you please share the full build logo? Sharing a https://gist.github.com would be a good way of doing it.

**Comment by bolinfest** [comment]
@jaimecbernardo Here you go: https://gist.github.com/bolinfest/0ab6440a94af4acc444dd05eafebd485

I see issues with trying to build for i386 on other Mac projects: https://github.com/ValveSoftware/Proton/issues/108

**Comment by bolinfest** [comment]
Here's another example of a change someone made to update their project for mojave:

https://github.com/the-tcpdump-group/libpcap/issues/781

It's hard to figure out where to do the same here because the configuration logic seems a bit spread out?

**Comment by bolinfest** [comment]
Yikes, reading all the way through the https://github.com/ValveSoftware/Proton/issues/108 thread, the "resolution" was to drop macOS support :(

**Comment by jaimecbernardo** [comment]
Hi @bolinfest ,

Thank you for the detailed log.

Looks like this is caused by the Xcode 10 deprecation of building for i86: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes?language=objc
> The macOS 10.14 SDK no longer contains support for compiling 32-bit applications. If developers need to compile for i386, Xcode 9.4 or earlier is required. (39858111)

So, one way of getting around this might be downloading Xode 9.4 and using it with `xcode-select` to select that version before building, as in these comments: https://github.com/mphoward/gsd-vmd/issues/2#issuecomment-471968702

This should still enable you to build 32-bit in Mojave.
Please let us know if it works.

**Comment by xuelongqy** [comment]
You can use Docker ubuntu on macOS
